repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.812
    hooks:
      - id: mypy

  - repo: https://github.com/psf/black.git
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort.git
    rev: 4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
